version : 0.0.2
container-name-run : "demo2"
container-name-tools : "bx-dev-demo2-tools"
image-name-run : "demo2"

image-name-tools : "my-microservice-image"
host-path-run : "target"
build-cmd-run : "mvn install -Dmaven.repo.local=/project/.m2/repository"
test-cmd : "mvn install -Dmaven.repo.local=/project/.m2/repository"
build-cmd-debug : "mvn install -Dmaven.repo.local=/project/.m2/repository"

container-path-run : "/project"
container-path-tools : "/project"

container-port-map : "9080:9080,9443:9443"
container-port-map-debug : "7777:7777"

dockerfile-run : "Dockerfile"
dockerfile-tools : "Dockerfile-tools"

debug-cmd : "server debug"
ibm-generated-id : "36c75055-9995-4cfd-858b-eddf9a1d36df"
credentials-filepath : "src/main/liberty/config/server.env, log.txt"